### ISSUE TITLE
Common headers missing

### ISSUE THREAD

**Issue by srijs** [blakeembrey/standard-headers#1]
The list is missing a few headers which are not strictly standardised, but are in common use, including:
- X-Forwarded-For
- X-Forwarded-Host
- X-Forwarded-Proto

A more complete list can be found here: http://en.wikipedia.org/wiki/List_of_HTTP_header_fields

Are there plans to include these headers in the list?

**Comment by blakeembrey** [comment]
I just switched to using the Wikipedia list and separated them into `request`/`response` headers.
